[project]
name = "equitabpfn-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "timeblock>=0.1.1",
    "tabpfn>=0.2.0",
    "numpy>=1.24.0",
    "mlflow>=3.7.0",
    "gpytorch>=1.14.3",
]
