
num_features: 100
n_samples: 1152
eval_positions_prop: 0.95
heterogeneous_batches: False
multiclass_loss_type: 'nono'
boolean:
  max_fraction_uninformative: 0.5
  p_uninformative: 0.5
prior_type: 'prior_bag'
prior_bag:
  prior_bag_exp_weights_1:
    distribution: 'uniform'
    min: 2.0
    max: 10.
mlp: 
  add_uninformative_features: False
  pre_sample_causes: True
  sampling: 'normal'
  prior_mlp_scale_weights_sqrt: True
  random_feature_rotation: True
  num_layers:
    distribution: 'meta_gamma'
    max_alpha: 2
    max_scale: 3
    round: True
    lower_bound: 2
  prior_mlp_hidden_dim: 
    distribution: 'meta_gamma'
    max_alpha: 3
    max_scale: 100
    round: True
    lower_bound: 4
  prior_mlp_dropout_prob: 
    distribution: 'meta_beta'
    scale: 0.6
    min: 0.1
    max: 5.0
  init_std: 
    distribution: 'log_uniform'
    min: 0.01
    max: 12
  noise_std: 
    distribution: 'log_uniform'
    min: 0.0001
    max: 0.5
  num_causes: 
    distribution: 'meta_gamma'
    max_alpha: 3
    max_scale: 7
    round: True
    lower_bound: 2
  is_causal: 
    distribution: 'meta_choice'
    choice_values: [True, False]

  pre_sample_weights: 
    distribution: 'meta_choice'
    choice_values: [True, False]
  y_is_effect: 
    distribution: 'meta_choice'
    choice_values: [True, False]
  prior_mlp_activations:
    distribution: 'meta_choice'
    choice_values: ['torch.nn.Tanh',
                    'torch.nn.Identity',
                    'torch.nn.ReLU']
  block_wise_dropout:
    distribution: 'meta_choice'
    choice_values: [True, False]
  sort_features:
    distribution: 'meta_choice'
    choice_values: [True, False]
  in_clique:
    distribution: 'meta_choice'
    choice_values: [True, False]

gp: 
  outputscale:
    distribution: 'log_uniform'
    min: 0.00001
    max: 8
  lengthscale:
    distribution: 'log_uniform'
    min: 0.00001
    max: 8
  noise:
    distribution: 'meta_choice'
    choice_values: [0.00001, 0.0001, 0.01]
  sampling: 'normal'           

classification:
  max_num_classes: 10
  num_classes: 
    distribution: 'uniform_int'
    min: 2
    max: 10
  num_features_used:
    distribution: 'uniform_int'
    min: 1
    max: 100
  
  balanced: False
  output_multiclass_ordered_p: 0.
  categorical_feature_p: 0.2
  multiclass_max_steps: 10
  multiclass_type: 'rank'
  nan_prob_unknown_reason_reason_prior: 0.5
  nan_prob_a_reason: 0.0
  nan_prob_no_reason: 0.0
  nan_prob_unknown_reason: 0.0
  set_value_to_nan: 0.1
